### ISSUE TITLE
How to do client side resizing?

### ISSUE THREAD

**Issue by jorgtron** [sheerun/s3_file_field#19]
This probably has a very simple answer, but how do I make client side resizing of images work with s3_file_field? (https://github.com/blueimp/jQuery-File-Upload/wiki/Client-side-Image-Resizing)

I've added the required JS files to the header as per that tutorial, and here is the code in my s3_file_field.js.coffee:

``` javascript
settings =
    # File input name must be "file"
    paramName: 'file'

    # S3 doesn't support multiple file uploads
    singleFileUploads: true

    # We don't want to send it to default form url
    url: url || $this.data('url')

    disableImageResize: false
    imageMaxWidth: 800
    imageMaxHeight: 800
    imageCrop: true 

...
```

The file uploads and everything works fine, but when I check the uploaded file it has not been resized. Am I setting the settings wrong?

**Comment by sheerun** [comment]
This library is deprecated in lieu of shrine: http://shrinerb.com/rdoc/files/doc/direct_s3_md.html
