### ISSUE TITLE
Can only select one batch of files

### ISSUE THREAD

**Issue by jumski** [sheerun/s3_file_field#20]
Hey!

I don't know if this is a feature or a bug, but I can only add photos with file dialog once.
After the first time i can still open file dialog but after choosing files nothing happens.

Am i missing something?

Thanks!

PS just moved from https://github.com/waynehoover/s3_direct_upload and works flawlessly, thanks!

**Comment by LaurelOlson** [comment]
Also having this issue. Anyone have a solution?

**Comment by sheerun** [comment]
Sincerely, you'd be better using something like shrine: http://shrinerb.com/

**Comment by sheerun** [comment]
http://shrinerb.com/rdoc/files/doc/direct_s3_md.html
