### ISSUE TITLE
Global acl initializer throwing exception

### ISSUE THREAD

**Issue by chrisdpeters** [sheerun/s3_file_field#25]
Per the README example, I tried configuring `acl` like this in `config/initializers/s3_file_field.rb`:

``` ruby
S3FileField.config do |c|
  ...
  c.acl = 'private'
end
```

And received this exception when starting the server:

```
undefined method `acl=' for #<S3FileField::Config:0x007f804b163730> (NoMethodError)
```

**Comment by sheerun** [comment]
This library is deprecated in lieu of shrine: http://shrinerb.com/rdoc/files/doc/direct_s3_md.html
