### ISSUE TITLE
Max file size

### ISSUE THREAD

**Issue by K1N5L4Y3R** [sheerun/s3_file_field#31]
This is not an actual issue but an advice. If you want to set the max file size, you need to do it directly on your view as so:

`<%= f.s3_file_field :avatar, max_file_size: 50.gigabytes, class: 'js-s3_file_field' %>`

I tried to do it on the config file as described on the readme, but it didn't work. I made a fork and added max_file_size to the attributes and this time the server ran correctly, but this didn't fix the issue with the max_file_size. The only thing that was needed was to do it in the view as previously described.

This should probably go in the README.

**Comment by sheerun** [comment]
This library is retired in lieu of shrine: http://shrinerb.com/rdoc/files/doc/direct_s3_md.html
