### ISSUE TITLE
Rename region to endpoint

### ISSUE THREAD

**Issue by Fs02** [sheerun/s3_file_field#32]
Based on the URL definition, isn't it better to rename region config to the endpoint? since the source code actually use the region as the endpoint.

```
    def url
      @url ||=
        if @options[:url]
          @options[:url]
        else
          protocol = @options[:ssl] == true ? "https" : @options[:ssl] == false ? "http" : nil
          subdomain = "#{@options[:bucket]}.#{@options[:region]}"
          domain = "//#{subdomain}.amazonaws.com/"
          [protocol, domain].compact.join(":")
        end
    end
```

https://github.com/sheerun/s3_file_field/blob/master/lib/s3_file_field/s3_uploader.rb#L64

**Comment by sheerun** [comment]
This library is retired in lieu of shrine: http://shrinerb.com/rdoc/files/doc/direct_s3_md.html
