### ISSUE TITLE
Support AWS Signature Version 4 for S3 uploads

### ISSUE THREAD

**Issue by kartikluke** [sheerun/s3_file_field#33]
I received this error message: "The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256." When using a bucket in the Mumbai region.

Further research shows:

[Amazon says here:](http://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html)

> Amazon S3 supports Signature Version 4, a protocol for authenticating inbound API requests to AWS services, in all AWS regions. At this time, existing AWS regions continue to support the previous protocol, Signature Version 2. Any new regions after January 30, 2014 will support only Signature Version 4 and therefore all requests to those regions must be made with Signature Version 4. Note that Signature Version 4 requires the request body to be signed for added security. This requirement creates additional computation load that is not required in Signature Version 2.

https://github.com/FineUploader/fine-uploader/issues/1336
Another file upload tool in JS allowing S3 has implemented support for Signature version 4. The process seems complicated but I'm sure it could be extracted into another library or something like that. Speaking to the people who worked on that could be a good idea.

Thanks.

**Comment by sheerun** [comment]
This library is retired in lieu of shrine: http://shrinerb.com/rdoc/files/doc/direct_s3_md.html
